# Generated by Django 4.2.29 on 2026-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikingstory',
            name='difficulty',
            field=models.CharField(choices=[('Лёгкий', 'Лёгкий'), ('Средний', 'Средний'), ('Сложный', 'Сложный')], default='Средний', max_length=30),
        ),
    ]
