# Generated by Django 4.2.29 on 2026-09-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('region', models.CharField(default='Алматинская область', max_length=150)),
                ('altitude', models.PositiveIntegerField(help_text='метров')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('moderate', 'Средний'), ('hard', 'Сложный')], default='moderate', max_length=30)),
                ('duration', models.CharField(default='1 день', max_length=80)),
                ('distance', models.CharField(blank=True, max_length=50)),
                ('season', models.CharField(default='Июнь — сентябрь', max_length=100)),
                ('description', models.TextField()),
                ('safety', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('latitude', models.FloatField(default=43.0)),
                ('longitude', models.FloatField(default=77.0)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
