# Generated by Django 4.2.29 on 2026-09-26 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mountains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('Одежда', 'Одежда'), ('Навигация', 'Навигация'), ('Еда и вода', 'Еда и вода'), ('Безопасность', 'Безопасность'), ('Кемпинг', 'Кемпинг')], max_length=40)),
                ('essential', models.BooleanField(default=True)),
                ('description', models.CharField(blank=True, max_length=240)),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('season', models.CharField(default='Лето', max_length=40)),
                ('duration_hours', models.PositiveSmallIntegerField(default=6)),
                ('group_size', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ManyToManyField(blank=True, to='hikes.equipment')),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to='mountains.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedHike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mountains.mountain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mountain')},
            },
        ),
    ]
