# Generated by Django 4.2.29 on 2026-09-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='season',
            field=models.CharField(choices=[('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень'), ('Зима', 'Зима')], default='Лето', max_length=40),
        ),
    ]
